# default: &default
#   adapter: 'sqlite3'
#   database: 'db/development.sqlite'

# development:
#   <<: *default

# test:
#   <<: *default
#   database: 'db/test.sqlite'

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000